USE [RPMProgrammingExcercise]
GO

/****** Object:  Table [dbo].[FuelPrices]    Script Date: 03/24/2023 00:41:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FuelPrices](
	[Period] [date] NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_FuelPrices] PRIMARY KEY CLUSTERED 
(
	[Period] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


